name: Update Anime Quote

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at noon
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Anime Quote
        run: |
          QUOTE=$(curl -s https://animechan.vercel.app/api/random | jq -r '"\(.quote)" — \(.character) from \(.anime)')
          sed -i "s|<p align=\"center\" id=\"anime-quote\">.*</p>|<p align=\"center\" id=\"anime-quote\">${QUOTE}</p>|" README.md
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Update anime quote"
          git push
